#!/bin/bash

sudo zypper refresh
sudo zypper up
sudo zypper install flatpak chromium xfce4-terminal cmus youtube-dl rtorrent vlc htop qalculate
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.valvesoftware.Steam
flatpak install flathub org.musicbrainz.Picard

