#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

if [ -f /var/run/reboot-required ]; then
  echo -e "${RED}reboot required${NOCOLOR}"
else
  echo -e "${GREEN}system updated, no reboot required${NOCOLOR}"
fi
