#!/bin/bash

sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak git chromium-browser terminator cmus youtube-dl rtorrent vlc htop qalc arc-theme
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.valvesoftware.Steam
flatpak install flathub org.musicbrainz.Picard
