#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

echo -e "${RED}updating repositories${NOCOLOR}"
sudo apt update
echo -e "${RED}upgrading system${NOCOLOR}"
sudo apt upgrade -y
echo -e "${RED}removing unnecessary software${NOCOLOR}"
sudo apt autoremove -y
echo -e "${RED}Updating flatpak apps${NOCOLOR}"
flatpak update
#echo -e "${RED}removing unnecessary flatpak apps${NOCOLOR}"
#flatpak uninstall --unused
#echo -e "${RED}Updating snaps${NOCOLOR}"
#sudo snap refresh
if [ -f /var/run/reboot-required ]; then
  notify-send -u critical -t 3000 "System updated!" "Reboot required"
  echo -e "${RED}reboot required${NOCOLOR}"
else
  notify-send -t 3000 "System updated!" "No reboot required"
  echo -e "${GREEN}system updated, no reboot required${NOCOLOR}"
fi
