#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

echo -e "${RED}updating repositories${NOCOLOR}"
sudo pacman -Sy
echo -e "${RED}upgrading system${NOCOLOR}"
sudo pacman -Su
echo -e "${RED}removing unnecessary software${NOCOLOR}"
sudo pacman -Qdtq | sudo pacman -Rs -
echo -e "${RED}Updating aur packages${NOCOLOR}"
pikaur -Sya
pikaur -Sua
