#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

echo -e "${RED}upgrading system${NOCOLOR}"
sudo dnf update -y
echo -e "${RED}removing unnecessary software${NOCOLOR}"
sudo dnf autoremove -y
echo -e "${RED}Updating flatpak apps${NOCOLOR}"
flatpak update
echo -e "${GREEN}system updated${NOCOLOR}"
notify-send "System updated!"
